// Auto-generated by LibreLane
module ic_top_usb_audio(
`ifdef USE_POWER_PINS
  inout VDD,
  inout VSS,
`endif
  input clk60mhz,
  input reset_n,
  output usb_dp_pull,
  output bitstream_out,
  inout usb_dp,
  inout usb_dn
);
endmodule
