// Auto-generated by LibreLane
module ic_top_usb_audio(
`ifdef USE_POWER_PINS
  inout VSS,
  inout VDD,
`endif
  output USB_DP_PULL,
  inout USB_DP,
  inout USB_DN,
  input SYS_CLK_60M,
  output DAC_MOD_OUT_L,
  input RESET_N
);
endmodule
