`timescale 1ns / 1ps
//--------------------------------------------------------------------------------------------------------
// Testbench : tb_usbfs_packet_rx
// DUT       : usbfs_packet_rx - extracts PID, ADDR/ENDP and data bytes, checks CRC5 and CRC16
//
// The testbench stands in for usbfs_bitlevel, driving the post-NRZI, post-de-stuff bit stream
// on rx_sta / rx_ena / rx_bit / rx_fin.
//
// Token packets are built here with an independent CRC5 (polynomial x^5+x^2+1, init 0x1F,
// residual inverted, transmitted MSB first) written from the USB specification.
// Data packets are generated by usbfs_packet_tx, which computes CRC16 independently.
//--------------------------------------------------------------------------------------------------------

module tb_usbfs_packet_rx;

    localparam [3:0] PID_OUT   = 4'h1;
    localparam [3:0] PID_IN    = 4'h9;
    localparam [3:0] PID_SOF   = 4'h5;
    localparam [3:0] PID_SETUP = 4'hD;
    localparam [3:0] PID_DATA0 = 4'h3;

    reg clk = 1'b0, rstn = 1'b0;
    always #8.333 clk = ~clk;

    reg        rx_sta = 1'b0, rx_ena = 1'b0, rx_bit = 1'b0, rx_fin = 1'b0;
    wire [3:0] rp_pid;
    wire[10:0] rp_addr;
    wire       rp_byte_en;
    wire [7:0] rp_byte;
    wire       rp_fin, rp_okay;

    usbfs_packet_rx dut (
        .rstn(rstn), .clk(clk),
        .rx_sta(rx_sta), .rx_ena(rx_ena), .rx_bit(rx_bit), .rx_fin(rx_fin),
        .rp_pid(rp_pid), .rp_addr(rp_addr), .rp_byte_en(rp_byte_en),
        .rp_byte(rp_byte), .rp_fin(rp_fin), .rp_okay(rp_okay)
    );

    integer errors = 0;
    integer nrx, i;
    reg [7:0] rxbuf [0:255];

    always @(posedge clk)
        if (rp_byte_en && nrx < 256) begin
            rxbuf[nrx] = rp_byte;
            nrx = nrx + 1;
        end

    function [4:0] crc5_step (input [4:0] crc, input inbit);
        reg xorbit;
        begin
            xorbit   = crc[4] ^ inbit;
            crc5_step = {crc[3:0], 1'b0} ^ {2'b0, xorbit, 1'b0, xorbit};
        end
    endfunction

    task automatic start_pkt;
        begin
            nrx = 0;
            @(posedge clk); #1;
            rx_sta = 1'b1;
            @(posedge clk); #1;
            rx_sta = 1'b0;
        end
    endtask

    task automatic send_bit (input b);
        begin
            rx_bit = b;
            rx_ena = 1'b1;
            @(posedge clk); #1;
            rx_ena = 1'b0;
            @(posedge clk); #1;
        end
    endtask

    task automatic end_pkt;
        begin
            rx_fin = 1'b1;
            @(posedge clk); #1;
            rx_fin = 1'b0;
            repeat (4) @(posedge clk);
            #1;
        end
    endtask

    // PID byte is {~pid, pid}, transmitted LSB first
    task automatic send_pid (input [3:0] pid, input corrupt_check);
        reg [7:0] b;
        integer k;
        begin
            b = {~pid, pid};
            if (corrupt_check) b[7] = ~b[7];      // break the complement nibble
            for (k = 0; k < 8; k = k + 1) send_bit(b[k]);
        end
    endtask

    // token = PID + 11 bits {endp[3:0], addr[6:0]} LSB first + 5 CRC bits
    task automatic send_token (input [3:0] pid, input [6:0] addr, input [3:0] endp,
                               input corrupt_crc);
        reg [10:0] f;
        reg [4:0]  crc;
        reg [4:0]  tx;
        integer    k;
        begin
            f   = {endp, addr};
            crc = 5'h1F;
            start_pkt;
            send_pid(pid, 1'b0);
            for (k = 0; k < 11; k = k + 1) begin
                send_bit(f[k]);
                crc = crc5_step(crc, f[k]);
            end
            tx = ~crc;
            if (corrupt_crc) tx = tx ^ 5'h01;
            for (k = 4; k >= 0; k = k - 1) send_bit(tx[k]);   // CRC5 transmitted MSB first
            end_pkt;
        end
    endtask

    task automatic check_token (input [3:0] pid, input [6:0] addr, input [3:0] endp,
                                input [255:0] label);
        begin
            send_token(pid, addr, endp, 1'b0);
            $display("  %-22s pid=%h addr=%02h endp=%h okay=%b",
                     label, rp_pid, rp_addr[6:0], rp_addr[10:7], rp_okay);
            if (rp_pid !== pid) begin
                $display("    ** FAIL: PID was %h, expected %h", rp_pid, pid);
                errors = errors + 1;
            end
            if (rp_addr[6:0] !== addr) begin
                $display("    ** FAIL: ADDR was %02h, expected %02h", rp_addr[6:0], addr);
                errors = errors + 1;
            end
            if (rp_addr[10:7] !== endp) begin
                $display("    ** FAIL: ENDP was %h, expected %h", rp_addr[10:7], endp);
                errors = errors + 1;
            end
            if (!rp_okay) begin
                $display("    ** FAIL: CRC5 rejected a well-formed token");
                errors = errors + 1;
            end
        end
    endtask

    initial begin
        $display("");
        $display("==========================================================================================");
        $display(" tb_usbfs_packet_rx : PID / token / CRC parsing");
        $display("==========================================================================================");
        $display("");

        rstn = 1'b0;
        repeat (10) @(posedge clk);
        rstn = 1'b1;
        repeat (5) @(posedge clk);

        $display(" token packets");
        check_token(PID_OUT,   7'h00, 4'h0, "OUT   addr 0 ep 0");
        check_token(PID_IN,    7'h05, 4'h2, "IN    addr 5 ep 2");
        check_token(PID_SETUP, 7'h01, 4'h0, "SETUP addr 1 ep 0");
        check_token(PID_SOF,   7'h7F, 4'hF, "SOF   (frame bits)");
        check_token(PID_OUT,   7'h2A, 4'h1, "OUT   addr 42 ep 1");

        $display("");
        $display(" error injection");

        send_token(PID_OUT, 7'h05, 4'h1, 1'b1);
        if (rp_okay) begin
            $display("  FAIL: a corrupted CRC5 was accepted");
            errors = errors + 1;
        end else begin
            $display("  OK: corrupted CRC5 rejected");
        end

        // PID with a broken complement nibble must not be accepted
        start_pkt;
        send_pid(PID_OUT, 1'b1);
        for (i = 0; i < 11; i = i + 1) send_bit(1'b0);
        for (i = 0; i < 5; i = i + 1) send_bit(1'b0);
        end_pkt;
        if (rp_okay) begin
            $display("  FAIL: a PID with a bad check nibble was accepted");
            errors = errors + 1;
        end else begin
            $display("  OK: PID with a bad check nibble rejected");
        end

        // a truncated packet must not report okay
        start_pkt;
        send_pid(PID_DATA0, 1'b0);
        for (i = 0; i < 3; i = i + 1) send_bit(1'b1);
        end_pkt;
        if (rp_okay) begin
            $display("  FAIL: a truncated packet was accepted");
            errors = errors + 1;
        end else begin
            $display("  OK: truncated packet rejected");
        end

        $display("");
        $display("==========================================================================================");
        if (errors == 0)
            $display(" RESULT: PASS - tokens parse correctly and malformed packets are rejected.");
        else
            $display(" RESULT: FAIL - %0d check(s) failed.", errors);
        $display("==========================================================================================");
        $display("");
        $finish;
    end

endmodule
