`timescale 1ns / 1ps
//--------------------------------------------------------------------------------------------------------
// Testbench : tb_usb_crc_conformance
//
// Conformance of the CRC machinery against the USB 2.0 full-speed requirements that the
// Basic Audio Device definition inherits (BADD builds on Audio 1.0, which builds on USB 2.0
// chapter 8: CRC5 protects token packets, CRC16 protects data packets, and a device must
// discard any packet whose CRC does not check).
//
// Vector counts:
//   CRC5  acceptance : 2048  - exhaustive over every 7-bit address x 4-bit endpoint
//   CRC5  rejection  : 2048  - every single-bit flip of the 5-bit CRC field, sampled tokens
//   CRC16 acceptance :   84  - lengths 0..64 crossed with four payload patterns
//   CRC16 rejection  :  280  - every single-bit position of a representative packet
//
// CRC5 is generated here from the polynomial in the USB specification, independently of the
// DUT. CRC16 is generated by usbfs_packet_tx and checked by usbfs_packet_rx, so the two
// independent implementations must agree.
//--------------------------------------------------------------------------------------------------------

module tb_usb_crc_conformance;

    localparam [3:0] PID_OUT   = 4'h1;
    localparam [3:0] PID_IN    = 4'h9;
    localparam [3:0] PID_SETUP = 4'hD;
    localparam [3:0] PID_DATA0 = 4'h3;

    reg clk = 1'b0, rstn = 1'b0;
    always #8.333 clk = ~clk;

    // ---- receiver under test ---------------------------------------------------------------------------
    reg        rx_sta = 1'b0, rx_ena = 1'b0, rx_bit = 1'b0, rx_fin = 1'b0;
    wire [3:0] rp_pid;
    wire[10:0] rp_addr;
    wire       rp_byte_en;
    wire [7:0] rp_byte;
    wire       rp_fin, rp_okay;

    usbfs_packet_rx rx (
        .rstn(rstn), .clk(clk),
        .rx_sta(rx_sta), .rx_ena(rx_ena), .rx_bit(rx_bit), .rx_fin(rx_fin),
        .rp_pid(rp_pid), .rp_addr(rp_addr), .rp_byte_en(rp_byte_en),
        .rp_byte(rp_byte), .rp_fin(rp_fin), .rp_okay(rp_okay)
    );

    // ---- transmitter used as an independent CRC16 generator ---------------------------------------------
    reg        tp_sta = 1'b0;
    reg  [3:0] tp_pid = 4'h0;
    wire       tp_byte_req;
    reg  [7:0] tp_byte = 8'h0;
    reg        tp_fin_n = 1'b1;
    reg        tx_req = 1'b0;
    wire       tx_bit, tx_fin, tx_sta;

    usbfs_packet_tx tx (
        .rstn(rstn), .clk(clk),
        .tp_sta(tp_sta), .tp_pid(tp_pid), .tp_byte_req(tp_byte_req),
        .tp_byte(tp_byte), .tp_fin_n(tp_fin_n),
        .tx_sta(tx_sta), .tx_req(tx_req), .tx_bit(tx_bit), .tx_fin(tx_fin)
    );

    integer plen = 0, byte_idx = 0, pattern = 0;

    // byte server for packet_tx
    always @(posedge clk)
        if (tp_byte_req) begin
            if (byte_idx < plen) begin
                case (pattern)
                    0: tp_byte <= 8'h00;
                    1: tp_byte <= 8'hFF;
                    2: tp_byte <= byte_idx[7:0];
                    default: tp_byte <= {$random} ^ (byte_idx[7:0] * 8'h9D);
                endcase
                tp_fin_n <= 1'b1;
            end else begin
                tp_byte  <= 8'h0;
                tp_fin_n <= 1'b0;
            end
            byte_idx <= byte_idx + 1;
        end

    integer errors, n_vec;
    integer i, j, k, nbits;
    reg [1023:0] bits;

    function [4:0] crc5_step (input [4:0] crc, input inbit);
        reg xorbit;
        begin
            xorbit    = crc[4] ^ inbit;
            crc5_step = {crc[3:0], 1'b0} ^ {2'b0, xorbit, 1'b0, xorbit};
        end
    endfunction

    task automatic send_bit (input b);
        begin
            rx_bit = b;
            rx_ena = 1'b1;
            @(posedge clk); #1;
            rx_ena = 1'b0;
            @(posedge clk); #1;
        end
    endtask

    task automatic start_pkt;
        begin
            @(posedge clk); #1;
            rx_sta = 1'b1;
            @(posedge clk); #1;
            rx_sta = 1'b0;
        end
    endtask

    task automatic end_pkt;
        begin
            rx_fin = 1'b1;
            @(posedge clk); #1;
            rx_fin = 1'b0;
            repeat (3) @(posedge clk); #1;
        end
    endtask

    // Drive a token; crc_flip < 0 means send a correct CRC.
    task automatic token (input [3:0] pid, input [6:0] addr, input [3:0] endp,
                          input integer crc_flip);
        reg [7:0]  pb;
        reg [10:0] f;
        reg [4:0]  crc, txc;
        begin
            pb  = {~pid, pid};
            f   = {endp, addr};
            crc = 5'h1F;
            start_pkt;
            for (k = 0; k < 8; k = k + 1) send_bit(pb[k]);
            for (k = 0; k < 11; k = k + 1) begin
                send_bit(f[k]);
                crc = crc5_step(crc, f[k]);
            end
            txc = ~crc;
            if (crc_flip >= 0) txc[crc_flip] = ~txc[crc_flip];
            for (k = 4; k >= 0; k = k - 1) send_bit(txc[k]);
            end_pkt;
        end
    endtask

    // Emit a DATA packet from packet_tx into `bits`.
    task automatic emit (input [3:0] pid, input integer len, input integer pat);
        begin
            nbits    = 0;
            plen     = len;
            pattern  = pat;
            byte_idx = 0;
            @(posedge clk); #1;
            tp_pid   = pid;
            tp_fin_n = 1'b1;
            tp_sta   = 1'b1;
            @(posedge clk); #1;
            tp_sta   = 1'b0;
            for (j = 0; j < 5000; j = j + 1) begin
                repeat (3) @(posedge clk);
                @(posedge clk); #1;
                tx_req = 1'b1;
                @(posedge clk); #1;
                tx_req = 1'b0;
                if (tx_fin) j = 5000;
                else begin
                    bits[nbits] = tx_bit;
                    nbits = nbits + 1;
                end
            end
        end
    endtask

    // Replay `bits` into packet_rx; flip < 0 means no corruption.
    task automatic replay (input integer n, input integer flip);
        begin
            start_pkt;
            for (k = 0; k < n; k = k + 1)
                send_bit((k == flip) ? ~bits[k] : bits[k]);
            end_pkt;
        end
    endtask

    initial begin
        errors = 0; n_vec = 0;

        $display("");
        $display("==========================================================================================");
        $display(" USB CRC conformance  (USB 2.0 chapter 8, inherited by UAC 1.0 / BADD)");
        $display("==========================================================================================");

        rstn = 1'b0;
        repeat (10) @(posedge clk);
        rstn = 1'b1;
        repeat (5) @(posedge clk);

        //================================================================================================
        $display("");
        $display(" 1. CRC5 acceptance - exhaustive over all 2048 address/endpoint combinations");
        $display("");
        begin : crc5_accept
            integer a, e, bad, badaddr;
            bad = 0; badaddr = 0;
            for (a = 0; a < 128; a = a + 1) begin
                for (e = 0; e < 16; e = e + 1) begin
                    token(PID_OUT, a[6:0], e[3:0], -1);
                    n_vec = n_vec + 1;
                    if (!rp_okay) bad = bad + 1;
                    if (rp_addr !== {e[3:0], a[6:0]}) badaddr = badaddr + 1;
                end
            end
            $display("  2048 tokens: CRC rejected %0d, address mis-decoded %0d", bad, badaddr);
            if (bad != 0) begin
                $display("    ** FAIL: a correctly formed CRC5 was rejected");
                errors = errors + 1;
            end else $display("    OK: every valid CRC5 accepted");
            if (badaddr != 0) begin
                $display("    ** FAIL: address/endpoint mis-decoded");
                errors = errors + 1;
            end else $display("    OK: every address/endpoint decoded correctly");
        end

        //================================================================================================
        $display("");
        $display(" 2. CRC5 rejection - every single-bit flip of the CRC field");
        $display("");
        begin : crc5_reject
            integer a, e, b, missed, tried;
            missed = 0; tried = 0;
            for (a = 0; a < 128; a = a + 4) begin
                for (e = 0; e < 16; e = e + 1) begin
                    for (b = 0; b < 5; b = b + 1) begin
                        token(PID_OUT, a[6:0], e[3:0], b);
                        n_vec = n_vec + 1;
                        tried = tried + 1;
                        if (rp_okay) missed = missed + 1;
                    end
                end
            end
            $display("  %0d corrupted tokens: accepted %0d (expected 0)", tried, missed);
            if (missed != 0) begin
                $display("    ** FAIL: corrupted CRC5 packets were accepted");
                errors = errors + 1;
            end else $display("    OK: every single-bit CRC5 error rejected");
        end

        //================================================================================================
        $display("");
        $display(" 3. CRC16 acceptance - payload lengths crossed with four patterns");
        $display("");
        begin : crc16_accept
            integer lens [0:20];
            integer nl, li, pat, bad, len;
            lens[0]=0;  lens[1]=1;  lens[2]=2;  lens[3]=3;  lens[4]=4;
            lens[5]=5;  lens[6]=7;  lens[7]=8;  lens[8]=15; lens[9]=16;
            lens[10]=17; lens[11]=23; lens[12]=24; lens[13]=31; lens[14]=32;
            lens[15]=33; lens[16]=47; lens[17]=48; lens[18]=63; lens[19]=64;
            nl  = 20;
            bad = 0;
            for (li = 0; li < nl; li = li + 1) begin
                for (pat = 0; pat < 4; pat = pat + 1) begin
                    len = lens[li];
                    emit(PID_DATA0, len, pat);
                    replay(nbits, -1);
                    n_vec = n_vec + 1;
                    if (!rp_okay || nbits != 8 + 8 * len + 16) bad = bad + 1;
                end
            end
            $display("  %0d packets across %0d lengths x 4 patterns: failures %0d", nl * 4, nl, bad);
            if (bad != 0) begin
                $display("    ** FAIL: a valid CRC16 packet did not round-trip");
                errors = errors + 1;
            end else $display("    OK: every valid CRC16 packet accepted, lengths framed correctly");
        end

        //================================================================================================
        $display("");
        $display(" 4. CRC16 rejection - every single-bit position of a 32-byte packet");
        $display("");
        begin : crc16_reject
            integer b, missed;
            emit(PID_DATA0, 32, 2);
            missed = 0;
            for (b = 0; b < nbits; b = b + 1) begin
                replay(nbits, b);
                n_vec = n_vec + 1;
                if (rp_okay) missed = missed + 1;
            end
            $display("  %0d single-bit corruptions: accepted %0d (expected 0)", nbits, missed);
            if (missed != 0) begin
                $display("    ** FAIL: %0d corrupted data packets were accepted", missed);
                errors = errors + 1;
            end else $display("    OK: every single-bit error in PID, payload or CRC rejected");
        end

        //================================================================================================
        $display("");
        $display(" 5. PID check-nibble conformance - all 16 PID values");
        $display("");
        begin : pid_check
            integer p, bad;
            reg [7:0] pb;
            bad = 0;
            for (p = 0; p < 16; p = p + 1) begin
                // correct complement nibble must be accepted as a token
                token(p[3:0], 7'h11, 4'h2, -1);
                n_vec = n_vec + 1;

                // corrupted complement nibble must never report okay
                pb = {~p[3:0], p[3:0]};
                pb[7] = ~pb[7];
                start_pkt;
                for (k = 0; k < 8; k = k + 1) send_bit(pb[k]);
                for (k = 0; k < 11; k = k + 1) send_bit(1'b0);
                for (k = 0; k < 5;  k = k + 1) send_bit(1'b0);
                end_pkt;
                n_vec = n_vec + 1;
                if (rp_okay) bad = bad + 1;
            end
            $display("  16 PIDs with broken check nibbles: accepted %0d (expected 0)", bad);
            if (bad != 0) begin
                $display("    ** FAIL: a PID with an invalid check nibble was accepted");
                errors = errors + 1;
            end else $display("    OK: PID check nibble enforced for every PID value");
        end

        $display("");
        $display("==========================================================================================");
        $display(" total vectors exercised: %0d", n_vec);
        if (errors == 0)
            $display(" RESULT: PASS - CRC5, CRC16 and PID checking all conform.");
        else
            $display(" RESULT: FAIL - %0d check group(s) failed.", errors);
        $display("==========================================================================================");
        $display("");
        $finish;
    end

endmodule
